// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test2.Data;

#nullable disable

namespace Test2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609123929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test2.Entities.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("AttendeeId");

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            AttendeeId = 1,
                            Email = "anna@email.com",
                            FirstName = "Anna",
                            LastName = "Kowalska",
                            Phone = "123456789"
                        },
                        new
                        {
                            AttendeeId = 2,
                            Email = "jan@email.com",
                            FirstName = "Jan",
                            LastName = "Nowak",
                            Phone = "234567891"
                        },
                        new
                        {
                            AttendeeId = 3,
                            Email = "maria@email.com",
                            FirstName = "Maria",
                            LastName = "Wisniewska",
                            Phone = "345678912"
                        },
                        new
                        {
                            AttendeeId = 4,
                            Email = "piotr@email.com",
                            FirstName = "Piotr",
                            LastName = "Zielinski",
                            Phone = "456789123"
                        },
                        new
                        {
                            AttendeeId = 5,
                            Email = "kasia@email.com",
                            FirstName = "Katarzyna",
                            LastName = "Lewandowska",
                            Phone = "567891234"
                        });
                });

            modelBuilder.Entity("Test2.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventDate = new DateTime(2026, 7, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Warsaw Jazz Festival",
                            Status = "Scheduled",
                            TicketPrice = 120.00m,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            EventDate = new DateTime(2026, 7, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Film Night",
                            Status = "Scheduled",
                            TicketPrice = 45.00m,
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            EventDate = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Modern Art Exhibition",
                            Status = "Completed",
                            TicketPrice = 30.00m,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            EventDate = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tech Conference 2026",
                            Status = "Scheduled",
                            TicketPrice = 200.00m,
                            VenueId = 4
                        },
                        new
                        {
                            EventId = 5,
                            EventDate = new DateTime(2026, 7, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Classical Music Evening",
                            Status = "Cancelled",
                            TicketPrice = 80.00m,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("Test2.Entities.Registration", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EventId", "AttendeeId");

                    b.HasIndex("AttendeeId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            AttendeeId = 1,
                            RegisteredAt = new DateTime(2026, 6, 20, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            SeatNumber = "C14"
                        },
                        new
                        {
                            EventId = 1,
                            AttendeeId = 2,
                            RegisteredAt = new DateTime(2026, 6, 21, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 2,
                            AttendeeId = 3,
                            RegisteredAt = new DateTime(2026, 6, 25, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EventId = 3,
                            AttendeeId = 4,
                            RegisteredAt = new DateTime(2026, 6, 15, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            SeatNumber = "A1"
                        },
                        new
                        {
                            EventId = 4,
                            AttendeeId = 5,
                            RegisteredAt = new DateTime(2026, 7, 1, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            SeatNumber = "R3"
                        },
                        new
                        {
                            EventId = 4,
                            AttendeeId = 1,
                            RegisteredAt = new DateTime(2026, 7, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SeatNumber = "R4"
                        });
                });

            modelBuilder.Entity("Test2.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "Marszalkowska 12, Warsaw",
                            Capacity = 500,
                            Name = "National Concert Hall",
                            Phone = "111222333"
                        },
                        new
                        {
                            VenueId = 2,
                            Address = "Lazienki Park 1, Warsaw",
                            Capacity = 1000,
                            Name = "Open Air Stage",
                            Phone = "222333444"
                        },
                        new
                        {
                            VenueId = 3,
                            Address = "Nowy Swiat 45, Warsaw",
                            Capacity = 120,
                            Name = "Gallery Nova",
                            Phone = "333444555"
                        },
                        new
                        {
                            VenueId = 4,
                            Address = "Zlota 59, Warsaw",
                            Capacity = 300,
                            Name = "City Conference Center",
                            Phone = "444555666"
                        });
                });

            modelBuilder.Entity("Test2.Entities.VenueDetails", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<string>("AccessibilityInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VenueId");

                    b.ToTable("VenueDetails");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            AccessibilityInfo = "Wheelchair ramps and elevator access",
                            ParkingSpaces = 150,
                            WebsiteUrl = "https://nch.example.com"
                        },
                        new
                        {
                            VenueId = 2,
                            AccessibilityInfo = "Flat terrain, accessible paths",
                            ParkingSpaces = 0
                        },
                        new
                        {
                            VenueId = 3,
                            AccessibilityInfo = "Ground floor only, no elevator",
                            ParkingSpaces = 30,
                            WebsiteUrl = "https://test321.example.com"
                        },
                        new
                        {
                            VenueId = 4,
                            AccessibilityInfo = "Full accessibility, hearing loop available",
                            ParkingSpaces = 200,
                            WebsiteUrl = "https://test123.example.com"
                        });
                });

            modelBuilder.Entity("Test2.Entities.Event", b =>
                {
                    b.HasOne("Test2.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Test2.Entities.Registration", b =>
                {
                    b.HasOne("Test2.Entities.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test2.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Test2.Entities.VenueDetails", b =>
                {
                    b.HasOne("Test2.Entities.Venue", "Venue")
                        .WithOne("VenueDetails")
                        .HasForeignKey("Test2.Entities.VenueDetails", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Test2.Entities.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Test2.Entities.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Test2.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("VenueDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
